# Generated by Django 3.2.2 on 2021-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('eater', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='foodapp/')),
            ],
        ),
    ]
